export const GETALLTASKS_SUCCESS = "GETALLTASKS_SUCCESS";
export const GETALLTASKS_FAIL = "GETALLTASKS_FAIL";
export const ADDTASK_SUCCESS = "ADDTASK_SUCCESS";
export const ADDTASK_FAIL = "ADDTASK_FAIL";
export const UPDATETASK_SUCCESS = "UPDATETASK_SUCCESS";
export const UPDATETASK_FAIL = "UPDATETASK_FAIL";
export const DELETETASK_SUCCESS = "DELETETASK_SUCCESS";
export const DELETETASK_FAIL = "DELETETASK_FAIL";